### ISSUE TITLE
"Grav.app" is damaged and can't be opened. You should move it to the trash.

### ISSUE THREAD

**Issue by 99robong** [TaehyunJeon0203/grav#2]
When I install and run the program (both 1.0.2 & 1.0.3),
the program is not opened and make an error 
"Grav.app" is damaged and can't be opened. You should move it to the trash.

<img width="266" alt="Screenshot 2024-11-13 at 18 32 22" src="https://github.com/user-attachments/assets/bcc5dbf0-465f-4f83-91e5-06234926753c">

OS Version: Sonoma 14.6.1
CPU: M2 Pro

**Comment by TaehyunJeon0203** [comment]
I checked the error.
This error appears to be due to the Mac's security feature 'GateKeeper'.
Would you like to disable it and try installing it?

**Comment by 99robong** [comment]
I don't know what the problem is but it still occurs same error.
So I build it myself and it work properly.
Thank You!
